<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BansosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bansos')->insert([
            [
                'status_rumah' => 1,
                'alas_rumah' => 4,
                'pekerjaan' => 4,
                'dinding_rumah' => 3,
                'luas_rumah' => 4,
                'besaran_listrik' => 3,
                'jumlah_tanggungan' => 5,
                'fasilitas_wc' => 2,
                'pendapatan' => 4,
                'jumlah_kendaraan' => 1,
                'nik' => '1234567890123450',
                'no_kk' => '1234567890123450',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'diterima',
                'id_notif' => null,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 1,
                'alas_rumah' => 1,
                'pekerjaan' => 3,
                'dinding_rumah' => 1,
                'luas_rumah' => 3,
                'besaran_listrik' => 2,
                'jumlah_tanggungan' => 4,
                'fasilitas_wc' => 1,
                'pendapatan' => 1,
                'jumlah_kendaraan' => 2,
                'nik' => '1234567890123451',
                'no_kk' => '1234567890123451',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'diterima',
                'id_notif' => null,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 2,
                'alas_rumah' => 1,
                'pekerjaan' => 2,
                'dinding_rumah' => 1,
                'luas_rumah' => 3,
                'besaran_listrik' => 2,
                'jumlah_tanggungan' => 5,
                'fasilitas_wc' => 1,
                'pendapatan' => 1,
                'jumlah_kendaraan' => 3,
                'nik' => '1234567890123452',
                'no_kk' => '1234567890123452',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'diterima',
                'id_notif' => null,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 1,
                'alas_rumah' => 2,
                'pekerjaan' => 4,
                'dinding_rumah' => 2,
                'luas_rumah' => 3,
                'besaran_listrik' => 3,
                'jumlah_tanggungan' => 3,
                'fasilitas_wc' => 1,
                'pendapatan' => 3,
                'jumlah_kendaraan' => 1,
                'nik' => '1234567890123453',
                'no_kk' => '1234567890123453',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'diterima',
                'id_notif' => null,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 2,
                'alas_rumah' => 1,
                'pekerjaan' => 1,
                'dinding_rumah' => 1,
                'luas_rumah' => 3,
                'besaran_listrik' => 2,
                'jumlah_tanggungan' => 4,
                'fasilitas_wc' => 1,
                'pendapatan' => 1,
                'jumlah_kendaraan' => 2,
                'nik' => '1234567890123454',
                'no_kk' => '1234567890123454',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'diterima',
                'id_notif' => null,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 2,
                'alas_rumah' => 1,
                'pekerjaan' => 3,
                'dinding_rumah' => 1,
                'luas_rumah' => 3,
                'besaran_listrik' => 3,
                'jumlah_tanggungan' => 5,
                'fasilitas_wc' => 1,
                'pendapatan' => 2,
                'jumlah_kendaraan' => 3,
                'nik' => '1234567890123455',
                'no_kk' => '1234567890123455',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'diterima',
                'id_notif' => null,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 2,
                'alas_rumah' => 1,
                'pekerjaan' => 2,
                'dinding_rumah' => 1,
                'luas_rumah' => 3,
                'besaran_listrik' => 2,
                'jumlah_tanggungan' => 4,
                'fasilitas_wc' => 1,
                'pendapatan' => 2,
                'jumlah_kendaraan' => 2,
                'nik' => '1234567890123456',
                'no_kk' => '1234567890123456',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'diterima',
                'id_notif' => null,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 1,
                'alas_rumah' => 4,
                'pekerjaan' => 3,
                'dinding_rumah' => 2,
                'luas_rumah' => 3,
                'besaran_listrik' => 3,
                'jumlah_tanggungan' => 3,
                'fasilitas_wc' => 1,
                'pendapatan' => 3,
                'jumlah_kendaraan' => 2,
                'nik' => '1234567890123457',
                'no_kk' => '1234567890123457',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'diterima',
                'id_notif' => null,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 2,
                'alas_rumah' => 1,
                'pekerjaan' => 4,
                'dinding_rumah' => 1,
                'luas_rumah' => 3,
                'besaran_listrik' => 3,
                'jumlah_tanggungan' => 3,
                'fasilitas_wc' => 1,
                'pendapatan' => 2,
                'jumlah_kendaraan' => 1,
                'nik' => '1234567890123458',
                'no_kk' => '1234567890123458',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'menunggu',
                'id_notif' => 9,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_rumah' => 1,
                'alas_rumah' => 3,
                'pekerjaan' => 4,
                'dinding_rumah' => 3,
                'luas_rumah' => 3,
                'besaran_listrik' => 3,
                'jumlah_tanggungan' => 2,
                'fasilitas_wc' => 2,
                'pendapatan' => 3,
                'jumlah_kendaraan' => 1,
                'nik' => '1234567890123459',
                'no_kk' => '1234567890123459',
                'jumlah_keluarga' => 3,
                'foto_gaji' => 'image 4_20240603_183247.png',
                'foto_sktm' => 'image 4_20240603_183247.png',
                'status_pengajuan' => 'menunggu',
                'id_notif' => 10,
                'tanggal_pengajuan' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
